[package]
name = "omnomnomicon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# actually used:
lexical-core = { version = "0.8", default-features = false, features=["std", "parse-integers", "parse-floats"] }
smallvec = { version = "1.6", features=["union"] }
bitflags = "1.3"

omnomnomicon_derive = { path = "./omnomnomicon_derive" }

ansi_term = { version = "0.12", optional = true }
rustyline = { version = "9.0", default-features = false, optional = true }

# for instances and tests
enum-map = { version = "1.1", default-features = false, optional = true }
chrono = { version = "0.4", optional = true }

[dev-dependencies]
omnomnomicon = { path = ".", features=["all"] }

[features]
default = []
tutorial = []
sanity = []
frontend_rustyline = ["ansi_term", "rustyline"]
all = ["tutorial", "frontend_rustyline", "sanity", "enum-map", "chrono"]
debug = []

[[example]]
name = "rustyline"
required-features = ["tutorial", "frontend_rustyline"]

[workspace]
members = [
    ".",
    "omnomnomicon_derive",
    "fuzz",
]




[package.metadata.docs.rs]
features = ["all"]
